import { counterTextField } from './js/textfieldCounter.js';
import { hideShowAnswer } from './js/hideShowAnswer.js';
import { bookmarkColoring } from './js/bookmarkColoring.js';
import { loginLogout } from './js/loginLogout.js';
import { navigation } from './js/navigation.js';
counterTextField();
hideShowAnswer();
bookmarkColoring();
loginLogout();
navigation();
